import { BrainCategory, BrainCategoryId, BrainExercise } from './types';

export const BRAIN_CATEGORIES: BrainCategory[] = [
  { id: 'memory', titleKey: 'brain.categories.memory.title', subtitleKey: 'brain.categories.memory.subtitle', icon: 'psychology' },
  { id: 'attention', titleKey: 'brain.categories.attention.title', subtitleKey: 'brain.categories.attention.subtitle', icon: 'visibility' },
  { id: 'reaction', titleKey: 'brain.categories.reaction.title', subtitleKey: 'brain.categories.reaction.subtitle', icon: 'bolt' },
  { id: 'logic', titleKey: 'brain.categories.logic.title', subtitleKey: 'brain.categories.logic.subtitle', icon: 'calculate' },
  { id: 'flexibility', titleKey: 'brain.categories.flexibility.title', subtitleKey: 'brain.categories.flexibility.subtitle', icon: 'track_changes' },
];

export const BRAIN_EXERCISES: BrainExercise[] = [
  {
    id: 'wordpuzzle',
    category: 'memory',
    titleKey: 'brain.exercises.wordpuzzle.title',
    subtitleKey: 'brain.exercises.wordpuzzle.subtitle',
    descriptionKey: 'brain.exercises.wordpuzzle.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy_time',
    uiTemplate: 'wordpuzzle',
    implemented: true,
  },
  {
    id: 'memory_story_gaps',
    category: 'memory',
    titleKey: 'brain.exercises.memoryStoryGaps.title',
    subtitleKey: 'brain.exercises.memoryStoryGaps.subtitle',
    descriptionKey: 'brain.exercises.memoryStoryGaps.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'fill_gaps',
    implemented: true,
  },
  {
    id: 'memory_objects',
    category: 'memory',
    titleKey: 'brain.exercises.memoryObjects.title',
    subtitleKey: 'brain.exercises.memoryObjects.subtitle',
    descriptionKey: 'brain.exercises.memoryObjects.description',
    difficulty: 'L1',
    estimatedMinutes: 4,
    scoringType: 'accuracy',
    uiTemplate: 'choice',
    implemented: true,
  },
  {
    id: 'memory_pairs_smoke',
    category: 'memory',
    titleKey: 'brain.exercises.memoryPairsSmoke.title',
    subtitleKey: 'brain.exercises.memoryPairsSmoke.subtitle',
    descriptionKey: 'brain.exercises.memoryPairsSmoke.description',
    difficulty: 'L1',
    estimatedMinutes: 4,
    scoringType: 'accuracy_time',
    uiTemplate: 'pairs',
    implemented: true,
  },
  {
    id: 'memory_word_bridge',
    category: 'memory',
    titleKey: 'brain.exercises.memoryWordBridge.title',
    subtitleKey: 'brain.exercises.memoryWordBridge.subtitle',
    descriptionKey: 'brain.exercises.memoryWordBridge.description',
    difficulty: 'L1',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'choice',
    implemented: true,
  },
  {
    id: 'memory_pairs_daily',
    category: 'memory',
    titleKey: 'brain.exercises.memoryPairsDaily.title',
    subtitleKey: 'brain.exercises.memoryPairsDaily.subtitle',
    descriptionKey: 'brain.exercises.memoryPairsDaily.description',
    difficulty: 'L1',
    estimatedMinutes: 6,
    scoringType: 'accuracy_time',
    uiTemplate: 'pairs',
    implemented: true,
  },
  {
    id: 'pairs-memory',
    category: 'memory',
    titleKey: 'brain.exercises.pairsMemory.title',
    subtitleKey: 'brain.exercises.pairsMemory.subtitle',
    descriptionKey: 'brain.exercises.pairsMemory.description',
    difficulty: 'L1',
    estimatedMinutes: 4,
    scoringType: 'accuracy_time',
    uiTemplate: 'pairs',
    implemented: false,
  },
  {
    id: 'number-sequence',
    category: 'memory',
    titleKey: 'brain.exercises.numberSequence.title',
    subtitleKey: 'brain.exercises.numberSequence.subtitle',
    descriptionKey: 'brain.exercises.numberSequence.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'sequence',
    implemented: false,
  },
  {
    id: 'picture-recall',
    category: 'memory',
    titleKey: 'brain.exercises.pictureRecall.title',
    subtitleKey: 'brain.exercises.pictureRecall.subtitle',
    descriptionKey: 'brain.exercises.pictureRecall.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'accuracy',
    uiTemplate: 'recall',
    implemented: false,
  },
  {
    id: 'pattern-fill',
    category: 'memory',
    titleKey: 'brain.exercises.patternFill.title',
    subtitleKey: 'brain.exercises.patternFill.subtitle',
    descriptionKey: 'brain.exercises.patternFill.description',
    difficulty: 'L3',
    estimatedMinutes: 6,
    scoringType: 'accuracy',
    uiTemplate: 'fill_gaps',
    implemented: false,
  },
  {
    id: 'focus-select',
    category: 'attention',
    titleKey: 'brain.exercises.focusSelect.title',
    subtitleKey: 'brain.exercises.focusSelect.subtitle',
    descriptionKey: 'brain.exercises.focusSelect.description',
    difficulty: 'L1',
    estimatedMinutes: 4,
    scoringType: 'speed_accuracy',
    uiTemplate: 'selection',
    implemented: false,
  },
  {
    id: 'logic_sequence_smoke',
    category: 'logic',
    titleKey: 'brain.exercises.logicSequenceSmoke.title',
    subtitleKey: 'brain.exercises.logicSequenceSmoke.subtitle',
    descriptionKey: 'brain.exercises.logicSequenceSmoke.description',
    difficulty: 'L1',
    estimatedMinutes: 4,
    scoringType: 'accuracy',
    uiTemplate: 'sequence',
    implemented: true,
  },
  {
    id: 'attention_odd_one_out',
    category: 'attention',
    titleKey: 'brain.exercises.attentionOddOneOut.title',
    subtitleKey: 'brain.exercises.attentionOddOneOut.subtitle',
    descriptionKey: 'brain.exercises.attentionOddOneOut.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'accuracy',
    uiTemplate: 'choice',
    implemented: true,
  },
  {
    id: 'attention_color_word',
    category: 'attention',
    titleKey: 'brain.exercises.attentionColorWord.title',
    subtitleKey: 'brain.exercises.attentionColorWord.subtitle',
    descriptionKey: 'brain.exercises.attentionColorWord.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'accuracy',
    uiTemplate: 'choice',
    implemented: true,
  },
  {
    id: 'attention_focus_filter',
    category: 'attention',
    titleKey: 'brain.exercises.attentionFocusFilter.title',
    subtitleKey: 'brain.exercises.attentionFocusFilter.subtitle',
    descriptionKey: 'brain.exercises.attentionFocusFilter.description',
    difficulty: 'L1',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'choice',
    implemented: true,
  },
  {
    id: 'attention_quick_read',
    category: 'attention',
    titleKey: 'brain.exercises.attentionQuickRead.title',
    subtitleKey: 'brain.exercises.attentionQuickRead.subtitle',
    descriptionKey: 'brain.exercises.attentionQuickRead.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'choice',
    implemented: true,
  },
  {
    id: 'symbol-search',
    category: 'attention',
    titleKey: 'brain.exercises.symbolSearch.title',
    subtitleKey: 'brain.exercises.symbolSearch.subtitle',
    descriptionKey: 'brain.exercises.symbolSearch.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'speed_accuracy',
    uiTemplate: 'search',
    implemented: false,
  },
  {
    id: 'odd-one-out',
    category: 'attention',
    titleKey: 'brain.exercises.oddOneOut.title',
    subtitleKey: 'brain.exercises.oddOneOut.subtitle',
    descriptionKey: 'brain.exercises.oddOneOut.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'accuracy',
    uiTemplate: 'choice',
    implemented: false,
  },
  {
    id: 'target-count',
    category: 'attention',
    titleKey: 'brain.exercises.targetCount.title',
    subtitleKey: 'brain.exercises.targetCount.subtitle',
    descriptionKey: 'brain.exercises.targetCount.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'count',
    uiTemplate: 'count',
    implemented: false,
  },
  {
    id: 'grid-scan',
    category: 'attention',
    titleKey: 'brain.exercises.gridScan.title',
    subtitleKey: 'brain.exercises.gridScan.subtitle',
    descriptionKey: 'brain.exercises.gridScan.description',
    difficulty: 'L3',
    estimatedMinutes: 6,
    scoringType: 'accuracy_time',
    uiTemplate: 'grid',
    implemented: false,
  },
  {
    id: 'go-no-go',
    category: 'reaction',
    titleKey: 'brain.exercises.goNoGo.title',
    subtitleKey: 'brain.exercises.goNoGo.subtitle',
    descriptionKey: 'brain.exercises.goNoGo.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'reaction_time',
    uiTemplate: 'go_no_go',
    implemented: false,
  },
  {
    id: 'stop-signal',
    category: 'reaction',
    titleKey: 'brain.exercises.stopSignal.title',
    subtitleKey: 'brain.exercises.stopSignal.subtitle',
    descriptionKey: 'brain.exercises.stopSignal.description',
    difficulty: 'L3',
    estimatedMinutes: 5,
    scoringType: 'reaction_time',
    uiTemplate: 'stop_signal',
    implemented: false,
  },
  {
    id: 'color-tap',
    category: 'reaction',
    titleKey: 'brain.exercises.colorTap.title',
    subtitleKey: 'brain.exercises.colorTap.subtitle',
    descriptionKey: 'brain.exercises.colorTap.description',
    difficulty: 'L1',
    estimatedMinutes: 3,
    scoringType: 'reaction_time',
    uiTemplate: 'timing',
    implemented: false,
  },
  {
    id: 'reaction_tap_smoke',
    category: 'reaction',
    titleKey: 'brain.exercises.reactionTapSmoke.title',
    subtitleKey: 'brain.exercises.reactionTapSmoke.subtitle',
    descriptionKey: 'brain.exercises.reactionTapSmoke.description',
    difficulty: 'L1',
    estimatedMinutes: 3,
    scoringType: 'reaction_time',
    uiTemplate: 'reaction',
    implemented: true,
  },
  {
    id: 'reaction_tap_target',
    category: 'reaction',
    titleKey: 'brain.exercises.reactionTapTarget.title',
    subtitleKey: 'brain.exercises.reactionTapTarget.subtitle',
    descriptionKey: 'brain.exercises.reactionTapTarget.description',
    difficulty: 'L1',
    estimatedMinutes: 4,
    scoringType: 'reaction_time',
    uiTemplate: 'reaction',
    implemented: true,
  },
  {
    id: 'reaction_go_nogo',
    category: 'reaction',
    titleKey: 'brain.exercises.reactionGoNoGo.title',
    subtitleKey: 'brain.exercises.reactionGoNoGo.subtitle',
    descriptionKey: 'brain.exercises.reactionGoNoGo.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'reaction_time',
    uiTemplate: 'reaction',
    implemented: true,
  },
  {
    id: 'quick-direction',
    category: 'reaction',
    titleKey: 'brain.exercises.quickDirection.title',
    subtitleKey: 'brain.exercises.quickDirection.subtitle',
    descriptionKey: 'brain.exercises.quickDirection.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'speed_accuracy',
    uiTemplate: 'timing',
    implemented: false,
  },
  {
    id: 'flash-number',
    category: 'reaction',
    titleKey: 'brain.exercises.flashNumber.title',
    subtitleKey: 'brain.exercises.flashNumber.subtitle',
    descriptionKey: 'brain.exercises.flashNumber.description',
    difficulty: 'L3',
    estimatedMinutes: 4,
    scoringType: 'timing_accuracy',
    uiTemplate: 'timing',
    implemented: false,
  },
  {
    id: 'sequence-logic',
    category: 'logic',
    titleKey: 'brain.exercises.sequenceLogic.title',
    subtitleKey: 'brain.exercises.sequenceLogic.subtitle',
    descriptionKey: 'brain.exercises.sequenceLogic.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'series',
    implemented: false,
  },
  {
    id: 'logic_next_in_series',
    category: 'logic',
    titleKey: 'brain.exercises.logicNextInSeries.title',
    subtitleKey: 'brain.exercises.logicNextInSeries.subtitle',
    descriptionKey: 'brain.exercises.logicNextInSeries.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'series',
    implemented: true,
  },
  {
    id: 'logic_order_steps',
    category: 'logic',
    titleKey: 'brain.exercises.logicOrderSteps.title',
    subtitleKey: 'brain.exercises.logicOrderSteps.subtitle',
    descriptionKey: 'brain.exercises.logicOrderSteps.description',
    difficulty: 'L1',
    estimatedMinutes: 6,
    scoringType: 'accuracy',
    uiTemplate: 'sequence',
    implemented: true,
  },
  {
    id: 'logic_reason_choice',
    category: 'logic',
    titleKey: 'brain.exercises.logicReasonChoice.title',
    subtitleKey: 'brain.exercises.logicReasonChoice.subtitle',
    descriptionKey: 'brain.exercises.logicReasonChoice.description',
    difficulty: 'L2',
    estimatedMinutes: 6,
    scoringType: 'accuracy',
    uiTemplate: 'choice',
    implemented: true,
  },
  {
    id: 'rule-switch',
    category: 'logic',
    titleKey: 'brain.exercises.ruleSwitch.title',
    subtitleKey: 'brain.exercises.ruleSwitch.subtitle',
    descriptionKey: 'brain.exercises.ruleSwitch.description',
    difficulty: 'L3',
    estimatedMinutes: 6,
    scoringType: 'speed_accuracy',
    uiTemplate: 'rule_switch',
    implemented: false,
  },
  {
    id: 'sorting-shapes',
    category: 'logic',
    titleKey: 'brain.exercises.sortingShapes.title',
    subtitleKey: 'brain.exercises.sortingShapes.subtitle',
    descriptionKey: 'brain.exercises.sortingShapes.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'sorting',
    implemented: false,
  },
  {
    id: 'grouping-sets',
    category: 'logic',
    titleKey: 'brain.exercises.groupingSets.title',
    subtitleKey: 'brain.exercises.groupingSets.subtitle',
    descriptionKey: 'brain.exercises.groupingSets.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'grouping',
    implemented: false,
  },
  {
    id: 'logic_grouping',
    category: 'logic',
    titleKey: 'brain.exercises.logicGrouping.title',
    subtitleKey: 'brain.exercises.logicGrouping.subtitle',
    descriptionKey: 'brain.exercises.logicGrouping.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'grouping',
    implemented: true,
  },
  {
    id: 'logic-paths',
    category: 'logic',
    titleKey: 'brain.exercises.logicPaths.title',
    subtitleKey: 'brain.exercises.logicPaths.subtitle',
    descriptionKey: 'brain.exercises.logicPaths.description',
    difficulty: 'L4',
    estimatedMinutes: 6,
    scoringType: 'accuracy_time',
    uiTemplate: 'maze',
    implemented: false,
  },
  {
    id: 'alternating-trail',
    category: 'flexibility',
    titleKey: 'brain.exercises.alternatingTrail.title',
    subtitleKey: 'brain.exercises.alternatingTrail.subtitle',
    descriptionKey: 'brain.exercises.alternatingTrail.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'speed_accuracy',
    uiTemplate: 'alternating',
    implemented: false,
  },
  {
    id: 'flex_reverse',
    category: 'flexibility',
    titleKey: 'brain.exercises.flexReverse.title',
    subtitleKey: 'brain.exercises.flexReverse.subtitle',
    descriptionKey: 'brain.exercises.flexReverse.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'accuracy',
    uiTemplate: 'reverse',
    implemented: true,
  },
  {
    id: 'flex_switch_rules',
    category: 'flexibility',
    titleKey: 'brain.exercises.flexSwitchRules.title',
    subtitleKey: 'brain.exercises.flexSwitchRules.subtitle',
    descriptionKey: 'brain.exercises.flexSwitchRules.description',
    difficulty: 'L3',
    estimatedMinutes: 5,
    scoringType: 'speed_accuracy',
    uiTemplate: 'rule_switch',
    implemented: true,
  },
  {
    id: 'flexibility_switch_order',
    category: 'flexibility',
    titleKey: 'brain.exercises.flexibilitySwitchOrder.title',
    subtitleKey: 'brain.exercises.flexibilitySwitchOrder.subtitle',
    descriptionKey: 'brain.exercises.flexibilitySwitchOrder.description',
    difficulty: 'L2',
    estimatedMinutes: 6,
    scoringType: 'accuracy',
    uiTemplate: 'sequence',
    implemented: true,
  },
  {
    id: 'flexibility_context_shift',
    category: 'flexibility',
    titleKey: 'brain.exercises.flexibilityContextShift.title',
    subtitleKey: 'brain.exercises.flexibilityContextShift.subtitle',
    descriptionKey: 'brain.exercises.flexibilityContextShift.description',
    difficulty: 'L2',
    estimatedMinutes: 5,
    scoringType: 'accuracy',
    uiTemplate: 'choice',
    implemented: true,
  },
  {
    id: 'verbal-fluency',
    category: 'flexibility',
    titleKey: 'brain.exercises.verbalFluency.title',
    subtitleKey: 'brain.exercises.verbalFluency.subtitle',
    descriptionKey: 'brain.exercises.verbalFluency.description',
    difficulty: 'L3',
    estimatedMinutes: 4,
    scoringType: 'accuracy',
    uiTemplate: 'verbal',
    implemented: false,
  },
  {
    id: 'reverse-digits',
    category: 'flexibility',
    titleKey: 'brain.exercises.reverseDigits.title',
    subtitleKey: 'brain.exercises.reverseDigits.subtitle',
    descriptionKey: 'brain.exercises.reverseDigits.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'accuracy_time',
    uiTemplate: 'reverse',
    implemented: false,
  },
  {
    id: 'spatial-matrix',
    category: 'flexibility',
    titleKey: 'brain.exercises.spatialMatrix.title',
    subtitleKey: 'brain.exercises.spatialMatrix.subtitle',
    descriptionKey: 'brain.exercises.spatialMatrix.description',
    difficulty: 'L3',
    estimatedMinutes: 6,
    scoringType: 'accuracy',
    uiTemplate: 'spatial',
    implemented: false,
  },
  {
    id: 'rhythm-pace',
    category: 'flexibility',
    titleKey: 'brain.exercises.rhythmPace.title',
    subtitleKey: 'brain.exercises.rhythmPace.subtitle',
    descriptionKey: 'brain.exercises.rhythmPace.description',
    difficulty: 'L2',
    estimatedMinutes: 4,
    scoringType: 'timing_accuracy',
    uiTemplate: 'rhythm',
    implemented: false,
  },
];

export const getExercisesByCategory = (categoryId: BrainCategoryId): BrainExercise[] =>
  BRAIN_EXERCISES.filter((exercise) => exercise.category === categoryId);

export const getExerciseById = (exerciseId: string): BrainExercise | undefined =>
  BRAIN_EXERCISES.find((exercise) => exercise.id === exerciseId);

