import { ChoiceRound } from '../types';

export const BANK_ID = 'flexibility.choiceText.v1';

export const items: ChoiceRound[] = [
  {
    id: `${BANK_ID}::q01`,
    prompt: "Tippe NICHT auf 'Ja'.",
    options: ['Ja', 'Nein', 'Vielleicht'],
    correctIndex: 1,
    hint: 'Denk an das Gegenteil.',
  },
  { id: `${BANK_ID}::q02`, prompt: "Antworte mit 'Nein', auch wenn es stimmt.", options: ['Ja', 'Nein', 'Unklar'], correctIndex: 1 },
  { id: `${BANK_ID}::q03`, prompt: 'Wähle das Gegenteil von heiß.', options: ['kalt', 'warm', 'leise', 'langsam'], correctIndex: 0 },
  { id: `${BANK_ID}::q04`, prompt: "Wenn du 'links' hörst, tippe rechts.", options: ['Links', 'Rechts', 'Mitte', 'Beides'], correctIndex: 1 },
  { id: `${BANK_ID}::q05`, prompt: 'Suche die kleinere Zahl.', options: ['9', '3', '7', '11'], correctIndex: 1 },
  { id: `${BANK_ID}::q06`, prompt: "Antwort ist immer 'Vielleicht'.", options: ['Ja', 'Nein', 'Vielleicht', 'Selten'], correctIndex: 2 },
  {
    id: `${BANK_ID}::q07`,
    prompt: "Wähle NICHT 'Grün'.",
    options: ['Blau', 'Rot', 'Grün', 'Gelb'],
    correctIndex: 1,
    hint: 'Vermeide Grün, wähle eine andere Farbe.',
  },
  { id: `${BANK_ID}::q08`, prompt: 'Tippe die zweite Option, nicht die erste.', options: ['Erste', 'Zweite', 'Dritte', 'Vierte'], correctIndex: 1 },
  {
    id: `${BANK_ID}::q09`,
    prompt: 'Regel A: Tippe die größte Zahl.',
    options: ['2', '7', '5', '9'],
    correctIndex: 3,
    hint: 'Gerade Runden = größte Zahl.',
  },
  {
    id: `${BANK_ID}::q10`,
    prompt: 'Regel B: Tippe die kleinste Zahl.',
    options: ['12', '3', '8', '6'],
    correctIndex: 1,
    hint: 'Ungerade Runden = kleinste Zahl.',
  },
  {
    id: `${BANK_ID}::q11`,
    prompt: 'Regel A: Tippe die größte Zahl.',
    options: ['4', '14', '10', '1'],
    correctIndex: 1,
    hint: 'Gerade Runden = größte Zahl.',
  },
  {
    id: `${BANK_ID}::q12`,
    prompt: 'Regel B: Tippe die kleinste Zahl.',
    options: ['20', '16', '18', '5'],
    correctIndex: 3,
    hint: 'Ungerade Runden = kleinste Zahl.',
  },
  {
    id: `${BANK_ID}::q13`,
    prompt: 'Regel A: Tippe die größte Zahl.',
    options: ['11', '9', '13', '2'],
    correctIndex: 2,
    hint: 'Gerade Runden = größte Zahl.',
  },
  {
    id: `${BANK_ID}::q14`,
    prompt: 'Regel B: Tippe die kleinste Zahl.',
    options: ['30', '25', '40', '27'],
    correctIndex: 1,
    hint: 'Ungerade Runden = kleinste Zahl.',
  },
  {
    id: `${BANK_ID}::q15`,
    prompt: 'Regel A: Tippe die größte Zahl.',
    options: ['6', '18', '12', '3'],
    correctIndex: 1,
    hint: 'Gerade Runden = größte Zahl.',
  },
  {
    id: `${BANK_ID}::q16`,
    prompt: 'Regel B: Tippe die kleinste Zahl.',
    options: ['5', '2', '9', '8'],
    correctIndex: 1,
    hint: 'Ungerade Runden = kleinste Zahl.',
  },
  { id: `${BANK_ID}::q17`, prompt: 'Wähle die zweite Option, obwohl die erste lockt.', options: ['Rot', 'Grün', 'Gelb', 'Blau'], correctIndex: 1 },
  { id: `${BANK_ID}::q18`, prompt: 'Antworte mit dem Wort, das nicht zur Farbe passt.', options: ['Sonne', 'Mond', 'Regen', 'Schnee'], correctIndex: 1 },
  { id: `${BANK_ID}::q19`, prompt: 'Regelwechsel: Wähle gerade Zahl.', options: ['5', '8', '7', '3'], correctIndex: 1 },
  { id: `${BANK_ID}::q20`, prompt: 'Regelwechsel: Wähle ungerade Zahl.', options: ['6', '10', '9', '12'], correctIndex: 2 },
  { id: `${BANK_ID}::q21`, prompt: 'Tippe das Wort, nicht das Symbol.', options: ['WORT', '★', '▲', '○'], correctIndex: 0 },
  { id: `${BANK_ID}::q22`, prompt: 'Wenn du eine Zahl siehst, wähle das Wort.', options: ['ZWÖLF', '12', '11', '13'], correctIndex: 0 },
  { id: `${BANK_ID}::q23`, prompt: 'Wechsle: erst kleinste, dann größte Zahl.', options: ['2', '9', '5', '7'], correctIndex: 0 },
  { id: `${BANK_ID}::q24`, prompt: 'Wechsle: jetzt größte Zahl.', options: ['4', '1', '3', '9'], correctIndex: 3 },
  {
    id: `${BANK_ID}::q25`,
    prompt: "Tippe NICHT auf 'Rot'.",
    options: ['Grün', 'Gelb', 'Rot', 'Blau'],
    correctIndex: 3,
    hint: 'Meide Rot in dieser Runde.',
  },
  { id: `${BANK_ID}::q26`, prompt: 'Tippe das Gegenteil von schwer.', options: ['leicht', 'schnell', 'lang', 'spät'], correctIndex: 0 },
  { id: `${BANK_ID}::q27`, prompt: 'Regel: Wenn ein Symbol da ist, wähle das Wort.', options: ['Haus', '☆', 'Baum', 'Wald'], correctIndex: 0 },
  { id: `${BANK_ID}::q28`, prompt: 'Regel: Wenn ein Wort da ist, wähle das Symbol.', options: ['Apfel', '☂', 'Mond', 'Klee'], correctIndex: 1 },
];

